alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: managed-premium-bind-wait
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - disableDeletion: true
          editable: true
          folder: sample
          name: sample
          options:
            path: /var/lib/grafana/dashboards/sample
          orgId: 1
          type: file
  dashboards:
    sample:
      kubernetes-cluster:
        datasource: Prometheus
        gnetId: 6417
  persistence:
    accessModes:
      - ReadWriteOnce
    enabled: true
    size: 5Gi
    storageClassName: managed-premium-bind-wait
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: managed-premium-bind-wait
prometheus-node-exporter:
  service:
    port: 30206
    targetPort: 30206
