name: "Repro"
on:
  issues:
    types:
      - labeled
      - unlabeled
defaults:
  run:
    shell: bash

jobs:
  terraform:
    if: github.event.label.name == 'repro'
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      TF_VAR_aks_cluster_name: ${{ github.actor }}-awesome-cluster-repro
      TF_VAR_aks_cluster_rg: rg-aks-awesome-cluster-repro
      TF_VAR_aks_cluster_location: japaneast
      TF_VAR_la_workspace_name: ${{ secrets.LA_WORKSPACE_NAME }}
      TF_VAR_la_workspace_rg: ${{ secrets.LA_WORKSPACE_RG }}
      TF_VAR_enable_flux: true
      TF_VAR_git_authuser: ${{ github.actor }}
      TF_VAR_git_authkey: ${{  secrets.GIT_AUTHKEY_FLUXREPO }}
      TF_VAR_git_fluxrepo: flux-demo
      ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{  secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Terraform Init"
        run: terraform init -backend-config=backend-repro.hcl
        working-directory: ./src/dev

      - name: "Terraform Format"
        run: terraform fmt -check
        working-directory: ./src/dev

      - name: "Terraform Plan"
        run: terraform plan -no-color
        working-directory: ./src/dev
